AZURE_LOCATION: 'westeurope'
RESOURCE_NAME_PREFIX: 'ase-ahms'
ENVIRONMENT_TAG: 'dev'
DEPLOYMENT_NAME: 'ase-demo-ahms'
VM_USERNAME: 'agent'
ACCOUNT_NAME: 'repalce me in repo secrets'
CICD_AGENT_TYPE: 'azuredevops'
